import React, { useState, useEffect, useRef } from 'react';

type Region = 'eyes' | 'lips' | 'full-face';

interface GenerateFilterResponse {
  imageBase64: string;
  error?: string;
}

interface FaceFilterStudioProps {
  initialPrompt?: string | null;
  initialRegion?: Region | null;
  autoGenerate?: boolean;
}

const BACKEND_BASE_URL =
  import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';

const FaceFilterStudio: React.FC<FaceFilterStudioProps> = ({
  initialPrompt,
  initialRegion,
  autoGenerate,
}) => {
  const [prompt, setPrompt] = useState(initialPrompt || '');
  const [region, setRegion] = useState<Region>(initialRegion || 'full-face');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterDataUrl, setFilterDataUrl] = useState<string | null>(null);
  const [recentFilters, setRecentFilters] = useState<string[]>([]);

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  // Request webcam access on mount
  useEffect(() => {
    const enableWebcam = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          video: { width: 640, height: 480 },
          audio: false,
        });
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
        }
      } catch (err) {
        console.error('Error accessing webcam:', err);
        setError('Could not access webcam. Please allow camera permissions.');
      }
    };

    enableWebcam();

    return () => {
      if (videoRef.current && videoRef.current.srcObject) {
        const tracks = (videoRef.current.srcObject as MediaStream).getTracks();
        tracks.forEach((track) => track.stop());
      }
    };
  }, []);

  // Auto-generate once if we were opened with a config from the advisor
  useEffect(() => {
    if (autoGenerate && !hasAutoGeneratedRef.current && initialPrompt && initialRegion) {
      hasAutoGeneratedRef.current = true;
      handleGenerate();
    }
  }, [autoGenerate, initialPrompt, initialRegion]);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setError(null);

    try {
      const res = await fetch(`${BACKEND_BASE_URL}/generate-filter`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: prompt.trim(),
          region,
        }),
      });

      const data: GenerateFilterResponse = await res.json();

      if (!res.ok || data.error) {
        setError(
          data.error || 'Failed to generate filter. Please try again later.',
        );
        return;
      }

      if (data.imageBase64) {
        const dataUrl = `data:image/png;base64,${data.imageBase64}`;
        setFilterDataUrl(dataUrl);
        setRecentFilters((prev) => [dataUrl, ...prev].slice(0, 6));
      } else {
        setError('Backend did not return image data.');
      }
    } catch (err) {
      console.error('Error calling backend:', err);
      setError('Network error while generating filter.');
    } finally {
      setIsLoading(false);
    }
  };

  const applyRecentFilter = (dataUrl: string) => {
    setFilterDataUrl(dataUrl);
  };

  const applyPresetPrompt = (value: string, presetRegion?: Region) => {
    setPrompt(value);
    if (presetRegion) setRegion(presetRegion);
  };

  // Simple layout constants for overlay sizing based on region
  const getOverlayStyle = (): React.CSSProperties => {
    if (!filterDataUrl) return { display: 'none' };

    let widthPercent = 0.7;
    let topPercent = 0.18;

    if (region === 'eyes') {
      widthPercent = 0.6;
      topPercent = 0.2;
    } else if (region === 'lips') {
      widthPercent = 0.35;
      topPercent = 0.6;
    }

    return {
      position: 'absolute',
      top: `${topPercent * 100}%`,
      left: '50%',
      transform: 'translate(-50%, -50%)',
      width: `${widthPercent * 100}%`,
      pointerEvents: 'none',
    };
  };

  return (
    <div className="flex flex-col gap-4 h-full p-4 bg-[#fdf6ec]">
      <div>
        <h2 className="text-2xl font-bold text-[#a48363]">
          Face Filter Studio
        </h2>
        <p className="text-sm text-[#7b5c3f]">
          Type a prompt, generate an AI face filter asset, and preview it on
          your webcam.
        </p>
      </div>

      <div className="flex flex-col md:flex-row gap-4">
        <div className="flex-1 space-y-3">
          <label className="block text-sm font-medium text-[#7b5c3f]">
            Prompt
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="mt-1 w-full p-2 border border-[#e3a66a] rounded-lg focus:outline-none focus:ring-2 focus:ring-[#e3a66a] min-h-[80px]"
              placeholder='e.g. "neon cyberpunk eyeliner with glowing blue highlights"'
            />
          </label>

          <div className="flex flex-wrap gap-2 text-sm">
            <button
              type="button"
              onClick={() =>
                applyPresetPrompt(
                  'neon cyberpunk eyeliner with glowing blue highlights',
                  'eyes',
                )
              }
              className="px-3 py-1 rounded-full bg-[#e3a66a] text-white hover:bg-[#a48363] transition-colors"
            >
              Neon eyeliner (eyes)
            </button>
            <button
              type="button"
              onClick={() =>
                applyPresetPrompt('comic-book superhero mask, bold colors', 'full-face')
              }
              className="px-3 py-1 rounded-full bg-[#e3a66a] text-white hover:bg-[#a48363] transition-colors"
            >
              Comic mask (full face)
            </button>
            <button
              type="button"
              onClick={() =>
                applyPresetPrompt('glossy red lipstick, subtle highlight', 'lips')
              }
              className="px-3 py-1 rounded-full bg-[#e3a66a] text-white hover:bg-[#a48363] transition-colors"
            >
              Glossy lips
            </button>
          </div>

          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-[#7b5c3f]">Region:</span>
              <label className="flex items-center gap-1 text-sm text-[#7b5c3f]">
                <input
                  type="radio"
                  name="region"
                  value="eyes"
                  checked={region === 'eyes'}
                  onChange={() => setRegion('eyes')}
                />
                Eyes
              </label>
              <label className="flex items-center gap-1 text-sm text-[#7b5c3f]">
                <input
                  type="radio"
                  name="region"
                  value="lips"
                  checked={region === 'lips'}
                  onChange={() => setRegion('lips')}
                />
                Lips
              </label>
              <label className="flex items-center gap-1 text-sm text-[#7b5c3f]">
                <input
                  type="radio"
                  name="region"
                  value="full-face"
                  checked={region === 'full-face'}
                  onChange={() => setRegion('full-face')}
                />
                Full face
              </label>
            </div>

            <button
              type="button"
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className={`px-4 py-2 rounded-lg text-white text-sm font-medium flex items-center gap-2 transition-colors ${
                isLoading || !prompt.trim()
                  ? 'bg-gray-400 cursor-not-allowed'
                  : 'bg-[#e3a66a] hover:bg-[#a48363]'
              }`}
            >
              {isLoading ? 'Generating…' : 'Generate filter'}
            </button>
          </div>

          {error && (
            <div className="mt-1 text-sm text-red-600 bg-red-50 border border-red-200 rounded p-2">
              {error}
            </div>
          )}
        </div>

        <div className="flex-1 flex flex-col gap-2">
          <div className="relative w-full max-w-xl mx-auto bg-black rounded-xl overflow-hidden aspect-video">
            <video
              ref={videoRef}
              autoPlay
              playsInline
              muted
              className="w-full h-full object-cover"
            />
            {filterDataUrl && (
              <img
                src={filterDataUrl}
                alt="Generated face filter overlay"
                style={getOverlayStyle()}
              />
            )}
            {!filterDataUrl && (
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <p className="text-sm text-white bg-black/50 px-3 py-1 rounded-lg">
                  Generated filter will appear here on top of your webcam
                </p>
              </div>
            )}
          </div>

          {recentFilters.length > 0 && (
            <div className="mt-2">
              <h3 className="text-sm font-semibold text-[#7b5c3f] mb-1">
                Recent filters
              </h3>
              <div className="flex flex-wrap gap-2">
                {recentFilters.map((dataUrl, index) => (
                  <button
                    key={index}
                    type="button"
                    onClick={() => applyRecentFilter(dataUrl)}
                    className="w-16 h-16 rounded-lg overflow-hidden border border-[#e3a66a] hover:border-[#a48363] transition-colors"
                  >
                    <img
                      src={dataUrl}
                      alt={`Recent filter ${index + 1}`}
                      className="w-full h-full object-cover"
                    />
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FaceFilterStudio;


